In [1]:
import sys
# Python 3.7 is required
assert sys.version_info >= (3,7)

import cv2 as cv
import numpy as np

# For reproducibility,
np.random.seed(99)

# Make sure that optimization is enabled
if not cv.useOptimized():
    cv.setUseOptimized(True)

cv.useOptimized()

True

# Weekly activity 4
1. Two ways to display multiple images
- open multile windows

In [15]:
img1 = cv.imread('lena.png')
img2 = cv.imread('dog.jfif')

cv.imshow('lena', img1)
cv.imshow('dog', img2)
cv.waitKey(0)
cv.destroyAllWindows()

- open in one window by utilizinig concatenation

In [13]:
img1 = cv.imread('lena.png')
img2 = cv.imread('dog.jfif')

print(img1.shape, '\t', img2.shape) # before resizing

(225, 225, 3) 	 (168, 300, 3)


In [17]:
# rezie the bigger image to fit with the smaller one
img1_resize = cv.resize(img1, (int(img1.shape[1] * img2.shape[0] / img1.shape[0]), # bigger image width * smaller image height / bigger image width = new resized height to maintain aspect ratio
                              img2.shape[0])) # use smaller image height
                               
print(img1_resize.shape, '\t', img2.shape)

(168, 168, 3) 	 (168, 300, 3)


In [18]:
# display image in concatenation
img_concat = cv.hconcat([img1_resize, img2])
cv.imshow('concat image', img_concat)
cv.waitKey(0)
cv.destroyAllWindows()

2. Write code to load the video, resize it and save it as seperate file

First find out the height, width and frame rate

In [37]:
# Create a VideoCapture object
cap = cv.VideoCapture('img_pexels.mp4')


# get height and width from frame.shape
ret, frame = cap.read()
height, width, layers = frame.shape

# get frame rate and print out width, height and frame rate
fps = cap.get(cv.CAP_PROP_FPS)
print (f"Height: {height}, Width: {width}, Frames per second(FPS): {fps}")

Height: 1920, Width: 1080, Frames per second(FPS): 60.0



Resize the video with smaller frame to display aand save

In [55]:
# get new height and width
new_height = height / 2.5 
new_width = width / 2.5


cap = cv.VideoCapture('img_pexels.mp4')

# Check if the object has been created successfully
if not cap.isOpened():
    print("Unable to create video")
    
# Define the codec and create VideoWriter object
fourcc = cv.VideoWriter_fourcc('M', 'J', 'P', 'G')
fps = 60
out = cv.VideoWriter('smaller_img_pexels.avi', fourcc, fps, (int(new_width), int(new_height)))

# Read until the video is completed.
while cap.isOpened():
    ret, frame = cap.read()
    
    # if frame is read then ret is True
    if not ret:
        print("Can't receive frame.")
        break
    
    frame_resize = cv.resize(frame, (int(new_width), int(new_height)))
    cv.imshow('frame', frame_resize)
    # write the frame to new file
    out.write(frame_resize)
    
    # to check the rezied frame size
    print(f"\r{frame_resize.shape}", end="")
    
    # Press Esc key to exit (27 is ASCII code for Esc). cv.waitKey() returns 32 bit integer values. You can find the ASCII table
    # on this URL: https://theasciicode.com.ar/
    if cv.waitKey(1) & 0xFF == 27:
        break

# destroy the constructor
cap.release()
out.release()
cv.destroyAllWindows()

(768, 432, 3)Can't receive frame.


3. create random noise color and grayscle image

Create 512x512 2d array with zeros

In [42]:
img = np.zeros((512, 512), dtype = np.uint8)
print(img, "\t", img.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 	 (512, 512)


convert 2d array with zeros into 3d array with 3 color channels

In [50]:
img_rgb = cv.cvtColor(img, cv.COLOR_GRAY2BGR)
img_rgb.shape

(512, 512, 3)

create random color image with cv.randu

In [49]:
random_img_rgb = cv.randu(img_rgb, (0, 0, 0), (255, 255, 255))
cv.imshow('random color image', random_img_rgb)
cv.waitKey(0)
cv.destroyAllWindows()

convert rnadom color image into grayscale image

In [54]:
gray_img = cv.cvtColor(random_img_rgb, cv.COLOR_BGR2GRAY)
 
cv.imshow('random grayscale image', gray_img)
cv.waitKey(0) 
cv.destroyAllWindows()